name: Build

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust targets
        run: |
          rustup target add x86_64-pc-windows-msvc
          rustup target add i686-pc-windows-msvc

      - name: Build 64-bit
        run: cargo build --target x86_64-pc-windows-msvc --release

      - name: Build 32-bit
        run: cargo build --target i686-pc-windows-msvc --release

      - name: Prepare release folders
        run: |
          mkdir x64
          mkdir x32
          copy target\x86_64-pc-windows-msvc\release\d3d11.dll x64\d3d11.dll
          copy target\i686-pc-windows-msvc\release\d3d11.dll x32\d3d11.dll

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            x64/d3d11.dll
            x32/d3d11.dll